name: 创建数据

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  createData:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      - name: 设置 Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: 运行脚本
        run: |
          cd actions_scripts
          node ./dist/createData.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
          AI_API_BASE_URL: ${{ vars.AI_API_BASE_URL }}
          LLM_MODEL: ${{ vars.LLM_MODEL }}
